### PR TITLE
.Bluetooth patch (master)

### PR DESCRIPTION
**Pull request by jakerockland**
This addresses #36 and replaces #74 which was closed due to swift-3.0 being merged to master.

### CODE REVIEW

**Comment by jakerockland** [comment]
It looks to me that this is failing the CI for other reasons that have to do with the current state of master and not actually with the changes in this PR, can you take a look @delba? I'd like to start integrating our project to use the current stable version of the framework rather than our fork but we need Bluetooth permissions to be fully functioning 😄 I believe this is ready to merge.

**Review by AndrewSB — APPROVED** [review]
This looks good to me @jakerockland 😄 we've been seeing some occasional weirdness with Bluetooth permission during on-boarding, hopefully this will resolve it

**Comment by jakerockland** [comment]
@AndrewSB Hopefully so, found this to resolve the issues I was having. If you're experiencing other weird behaviour that this patch doesn't fix I would be happy to look into it as it may be an edge case we just haven't seen yet but that would effect our application as well 😛

**Comment by AndrewSB** [comment]
Will let you know, I'm probably going to end up debugging that
Wednesday/Thursday this week

**Comment by delba** [comment]
Thanks @jakerockland ! If it's okay, I would like to get back to you later because I'm still a bit confused though... Do you have an email?

Also, if you (@jakerockland, @AndrewSB) have an opinion on #35, I'd be really interested to hear it. I'm still undecided and I don't want to make a breaking change just after releasing the `swift 3.0` version.

Thanks guys 😃

**Comment by delba** [comment]
I reverted the PR as there were still many issues with the bluetooth permission:
- the call `CBPeripheralManager - state` was triggering system authorization request when the app had background mode capabilities
- the state (`CBPeripheralManagerState`) was returning `.unknown` instead of `.authorized` `peripheralManagerDidUpdateState` wasn't called during the app lifecycle (but the correct state if `.denied` etc.)
- the permission callback could be triggered twice

These issues have been fixed in https://github.com/delba/Permission/commit/f6b36cebcc72f2f99148b05cc813774d9a87972b

**Comment by jakerockland** [comment]
Hey @delba haven't got a chance to test this yet but I looked over your changes and they look good to me generally. I hadn't ran into those edge cases yet so I'm glad you caught them 😅 Definitely feel free to email me anytime though! jake@somaticlabs.io

**Comment by jakerockland** [comment]
Will be pulling the new v2.0 release and testing things out soon! 👍

**Pull request merged**
