### PR TITLE
Reimplemented DispatchQueue extension

### PR DESCRIPTION
**Pull request by jakerockland**

### CODE REVIEW

**Comment by jakerockland** [comment]
@delba I think we may actually want the DispatchQueue extension implemented? Otherwise there is a compile error in `Notifications.swift` line 63

**Comment by jakerockland** [comment]
@delba I think we may actually want the DispatchQueue extension implemented? Otherwise there is a compile error in `Notifications.swift` line 63

**Comment by delba** [comment]
Could you please rebase with `swift-3.0` ?

``` swift
extension DispatchQueue {
    func after(_ interval: DispatchTimeInterval, execute: () -> Void) {
        after(interval, execute: execute)
    }
}
```

Why would it throw a compile error when removed? I don't have Xcode 8 installed 🙈

**Comment by jakerockland** [comment]
Just went ahead and rebased @delba, the issue is that without the extension, DispatchQueue doesn't have an after method, which is called in `Notifications.swift`. I may be missing something though 😛

**Comment by delba** [comment]
Ok I'll figure out that later but for now....Merge!
:joy: tanks Jake

**Pull request merged**
