### PR TITLE
Action styles

### PR DESCRIPTION
**Pull request by jakerockland**
This is a response to #82

### CODE REVIEW

**Comment by delba** [comment]
@jakerockland Could you rebase please ?

**Comment by jakerockland** [comment]
@delba Yeah sorry about this PR being a bit messy, still getting comfortable with contributing to open source projects 😅.

**Comment by jakerockland** [comment]
I think it should be good for merge now @delba 😄

**Comment by jakerockland** [comment]
@delba Not exactly sure why this is failing CI, but I think it can be merged, could you check this out?

**Comment by delba** [comment]
Could you use `preferredAction` too, please?
https://developer.apple.com/reference/uikit/uialertcontroller/1620102-preferredaction

**Comment by jakerockland** [comment]
@delba Sure thing, just pushed a change that implements that.

I'm don't think its *necessary* to have it in the default cancel alert action, but I also don't think it hurts at so I erred on the side of consistency.

```
    var controller: UIAlertController {
        let controller = UIAlertController(title: title, message: message, preferredStyle: .alert)
        
        let action = UIAlertAction(title: cancelActionTitle, style: .cancel, handler: cancelHandler)
        controller.addAction(action)

        if #available(iOS 9.0, *) {
            controller.preferredAction = action
        }
        
        return controller
    }
```

Thoughts?

**Comment by delba** [comment]
It's a bit confusing to set it for the cancel handler, I would rather not have it please

**Comment by jakerockland** [comment]
Makes sense, I agree its a bit confusing and isn't necessary. Just wanted to err on consistency, but do think its better without, just pushed a change that removes it.

**Comment by delba** [comment]
Thanks @jakerockland !

**Comment by jakerockland** [comment]
No problem! 😄

**Pull request merged**
