### PR TITLE
Swift 4.0 compatibility 

### PR DESCRIPTION
**Pull request by rsaarloos**
Small changes required to make the pod build with XCode 9.0 and Swift 4.0

Also related to #116

### CODE REVIEW

**Comment by rsaarloos** [comment]
@delba can you have a look at the PR?

**Review by WesleyBuck — APPROVED** [review]

**Comment by joihelgi** [comment]
@rsaarloos @WesleyBuck @delba merge?

**Comment by rsaarloos** [comment]
@joihelgi I don't have the write access to merge the pull request. @delba can you please help out here and merge and push a repo update to Cocoapods

**Comment by jonandersen** [comment]
Been using this for a while. Works well

**Comment by yousifa** [comment]
can someone merge this pls?

**Comment by linksmt** [comment]
@delba Can you merge?

**Comment by gorbat-o** [comment]
Hey guys,

I am also waiting the merge of this 💯 
Thank you :)

**Comment by marcosjvivar** [comment]
@delba Do we have an ETA on when this PR is going to be merged, if at all???
Lovely work @rsaarloos! 🚀 
Keep pushing for this merge!

**Comment by drbarto** [comment]
Any news on this, or has someone created a public fork using the PR?

**Comment by delba** [comment]
Hi @rsaarloos, thank you very much for the PR.
The project has been updated to the latest Swift version, there were many tweaks involved.
Thanks again :)

**Pull request closed without merging**
