### PR TITLE
Fixed so confirm actions are now bold...

### PR DESCRIPTION
**Pull request by justinmakaila**
apparently someone got uncomfortable with our confirm actions saying `.cancel` ;)

This should be good to go straight into master afterwards.

### CODE REVIEW

**Comment by delba** [comment]
Ahahah yes indeed, I wasn't at all :)

Could you create a separate request with only   f03e703 please ? The other commits look very interesting but I will have to test them first...

Thanks @justinmakaila !

**Comment by justinmakaila** [comment]
Removing the old commits now

**Comment by justinmakaila** [comment]
@delba This is reverted back to the bold confirmation state. Ready for review and merge.

**Comment by delba** [comment]
Hi @justinmakaila !

I cherry picked f03e703 and merged it here https://github.com/delba/Permission/commit/b83ed68c1bc69351bef4655460cf23b9ceba3990

Thank you 👏

**Pull request closed without merging**
