### PR TITLE
Swift 3.0 beta 1

### PR DESCRIPTION
**Pull request by hartbit**

### CODE REVIEW

**Comment by delba** [comment]
Thank you!!

**Comment by jakerockland** [comment]
@delba @hartbit Are you able to get this to build for XCode 8.0 beta? I'm trying to build with `carthage update --platform iOS` and am having the build fail with:

```
The following build commands failed:
    CompileSwift normal arm64
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
```

**Comment by hartbit** [comment]
@jakerockland I've opened a pull-request that makes Permission build on beta3 #39

**Comment by delba** [comment]
@jakerockland It got merged. Thanks @hartbit !

**Comment by delba** [comment]
Hi @hartbit,

I was wondering why `func callbacks(status: PermissionStatus)` was renamed `func callbackAsync(with: PermissionStatus)` ?

**Comment by hartbit** [comment]
@delba I probably renamed it for several reasons:
- The orignal name was not a verb
- I wanted to make it crystal clear it was an asynchronous operation
- I also wanted to follow more closely then among rules which take more advantage of the first argument label. In Objective-C, I guess the function would have been named `callbackAsyncWithStatus:`

**Comment by delba** [comment]
I got you but it can also be a bit confusing too and lead to think that the difference between `callback` and `callbackAsync` is that one is asynchronous and the other isn't.
https://github.com/delba/Permission/commit/13b2512ae3c6f23aadbaedef49ed9e780ee2da8c

**Comment by hartbit** [comment]
Which `callback`? The property? Well in that case I'm not sure I see the problem. One is a function which is explicitly named as being asynchronous (and it is), and the other one is a closure given at configuration time and which makes no promises of asynchronosity one way or the other.

Perhaps if you want to completely remove any potential ambiguity, we should call the property `completionHandler` and the function `completeAsync`. One idea. Perhaps you have another one?

**Comment by delba** [comment]
In addition of having a similar name, `callback` and `callbackAsync` have the same type (`Callback` which is an alias for `PermissionStatus -> Void`) and both are passed around the lib hence the risk of confusion. They both are callable even tough one is a property and the other one a method: `callback(status)` and `callbackAsync(status)`.

The risk is to think that `callbackAsync` is only this:

``` swift
func callbackAsync(status: PermissionStatus) {
    async { callback(status) }
}
```

I initially named it `callbacks` (plural) because it contains all the callbacks that should be called once the permission has been requested: not only the user defined `callback` but also the permissionSets delegate method `didRequestPermission`.

It's not perfect either I agree. Naming is hard ;)

**Comment by hartbit** [comment]
What do you think of ˋcompletionHandler`and ˋcompleteAsync` then?

**Pull request merged**
