### PR TITLE
update for swift 2.2 & fixed notificationTimer selector which is missing

### PR DESCRIPTION
**Pull request by sairamkotha**

### CODE REVIEW

**Comment by albinekcom** [comment]
You need to change from: `osx_image: xcode7.1` to `osx_image: xcode7.3` in `.travis.yml` file to fix building. Xcode 7.3 is the minimum version of IDE which supports Swift 2.2 function `#selector()`.

**Comment by sairamkotha** [comment]
Updated travis

**Comment by albinekcom** [comment]
I thought about adding that in this commit to make the build passing.

**Comment by delba** [comment]
Hi @sairamkotha, thanks for your contribution :)

As @albinekcom suggested, could you please add #3 to this PR and rebase it?

Thank you!

**Comment by sairamkotha** [comment]
Please check now @delba  updated travis ..Merge now

**Comment by delba** [comment]
Rebase please

**Comment by sairamkotha** [comment]
Please check now and merge it. Thanks for patience

**Comment by delba** [comment]
@sairamkotha I'm sorry but your branch still had conflicts and therefore I couldn't merge it.

I updated to `#selector` in e857f7e45cefd6cf36131f56e865d23171d4ab0c.

Thank you!

**Pull request closed without merging**
